
runtime: go
api_version: go1

handlers:
- url: /.*
  script: _go_app

env_variables:
<<<<<<< HEAD:app.yaml
  HUB_VERIFY_TOKEN: '6b9b71fc-7ace-495d-85da-d0568349f587'
=======
  HUB_VERIFY_TOKEN: "Verify Token"
  PAGE_TOKEN: "Page Token"
>>>>>>> master:appengine/chat_module/app.yaml
