api_version: go1
handlers:
- login: admin
  script: _go_app
  url: /api/.*
- login: admin
  static_dir: static
  url: /static
- login: admin
  static_files: index.html
  upload: index.html
  url: /.*
runtime: go
service: admin
